### ISSUE TITLE
Automatic Approval Failing

### ISSUE THREAD

**Issue by jax-b** [Keyfactor/ejbca-cert-manager-issuer#83]
Hi there i followed your [guide](https://docs.keyfactor.com/ejbca/8.3.2/tutorial-use-ejbca-with-cert-manager) on getting the plugin set up. but im having a issue getting the certificate request approved in cert-manager. 

when approved with cmcli the certificate does get issued from ejbca.

Specifically getting the below error when using either the cluster issuer or the regular issuer.
```
 err="admission webhook \"webhook.cert-manager.io\" denied the request: status.conditions: Forbidden: user \"system:serviceaccount:cert-manager:cert-manager\" does not have permissions to set approved/denied conditions for issuer {clusterissuer-pkirules ClusterIssuer ejbca-issuer.keyfactor.com}" logger="cert-manager.controller"
```

I'm wondering if you have a recommended resolution?

My whole setup is deployed through an ansible playbook.
```
    - name: Setup cert-manager + EJBCA Issuer
      tags:
        - cert-manager
      block:
        # The V1 Certificates API must be enabled within the EJBCA Admin UI
        # The End Entity Profile must be configured with the DNS name for the internal service
        # The RA configuration must be setup per (https://docs.keyfactor.com/ejbca/9.0/tutorial-use-ejbca-with-cert-manager)
        - name: Install cert-manager
          kubernetes.core.helm:
            kubeconfig: "{{ KUBECONFIG }}"
            name: cert-manager
            chart_ref: jetstack/cert-manager
            release_namespace: cert-manager
            create_namespace: true
            values:
              installCRDs: true

        - name: Create the ejbca-cert-manager and pkirules namespaces
          kubernetes.core.k8s:
            kubeconfig: "{{ KUBECONFIG }}"
            state: present
            api_version: v1
            kind: Namespace
            name: "{{ item }}"
          with_items:
            - ejbca-cert-manager
            - pkirules

        - name: Decrypt EJBCA RA Key
          ansible.builtin.command: |-
            openssl pkcs12 -in certs/cert-manager-ra-01.p12 -nodes --passin pass:{{- cert_manager.keystore_pin -}} -nocerts
          changed_when: false
          register: ejbca_ra_key

        - name: Decrypt EJBCA RA Cert
          ansible.builtin.command: |-
            openssl pkcs12 -in certs/cert-manager-ra-01.p12 -nodes --passin pass:{{- cert_manager.keystore_pin -}} -clcerts -nokeys
          changed_when: false
          register: ejbca_ra_cert

        - name: Decrypt EJBCA CA Cert
          ansible.builtin.command: |-
            openssl pkcs12 -in certs/cert-manager-ra-01.p12 -nodes --passin pass:{{- cert_manager.keystore_pin -}} -cacerts -nokeys
          changed_when: false
          register: ejbca_ca_cert

        - name: Setup RA Secret
          kubernetes.core.k8s:
            kubeconfig: "{{ KUBECONFIG }}"
            state: present
            api_version: v1
            kind: Secret
            name: ejbca-secret
            namespace: "{{ item }}"
            definition:
              type: kubernetes.io/tls
              data:
                tls.key: "{{ ejbca_ra_key.stdout | b64encode }}"
                tls.crt: "{{ ejbca_ra_cert.stdout | b64encode }}"
          with_items:
            - ejbca-cert-manager
            # - pkirules

        - name: Setup CA Chain
          kubernetes.core.k8s:
            kubeconfig: "{{ KUBECONFIG }}"
            state: present
            api_version: v1
            kind: Secret
            name: ejbca-ca-secret
            namespace: "{{ item }}"
            definition:
              type: generic
              data:
                ca.crt: "{{ ejbca_ca_cert.stdout | b64encode }}"
          with_items:
            - ejbca-cert-manager
            # - pkirules

        - name: Install EJBCA Issuer Service
          kubernetes.core.helm:
            kubeconfig: "{{ KUBECONFIG }}"
            name: ejbca-cert-manager-issuer
            chart_ref: ejbca-issuer/ejbca-cert-manager-issuer
            release_namespace: ejbca-cert-manager
            create_namespace: true
            values:
              image.tag: "1.3.2"

        - name: Setup the EJBCA Issuer config
          kubernetes.core.k8s:
            kubeconfig: "{{ KUBECONFIG }}"
            state: present
            api_version: ejbca-issuer.keyfactor.com/v1alpha1
            kind: Issuer
            name: pkirule-tls
            namespace: pkirules
            definition:
              spec:
                hostname: ejbca-ejbca-community-helm-nginx.keyfactor.svc.cluster.local
                ejbcaSecretName: ejbca-secret
                certificateAuthorityName: "{{ cert_manager.issuing_ca }}"
                certificateProfileName: "{{ cert_manager.certificate_profile }}"
                endEntityProfileName: "{{ cert_manager.end_entity_profile }}"
                caBundleSecretName: ejbca-ca-secret

        - name: Setup the EJBCA Cluster Issuer config
          kubernetes.core.k8s:
            kubeconfig: "{{ KUBECONFIG }}"
            state: present
            api_version: ejbca-issuer.keyfactor.com/v1alpha1
            kind: ClusterIssuer
            name: clusterissuer-pkirules
            namespace: pkirules
            definition:
              spec:
                hostname: ejbca-ejbca-community-helm-nginx.keyfactor.svc.cluster.local
                ejbcaSecretName: ejbca-secret
                certificateAuthorityName: "{{ cert_manager.issuing_ca }}"
                certificateProfileName: "{{ cert_manager.certificate_profile }}"
                endEntityProfileName: "{{ cert_manager.end_entity_profile }}"
                caBundleSecretName: ejbca-ca-secret
```

**Comment by jax-b** [comment]
Actually looks like this has already been solved! in issue #29. I'm working on a proper fix now.

**Comment by jax-b** [comment]
Working with the additional roles

```
        - name: Create ClusterRole to allow for cert-manager to approve certs for the EJBCA Issuer certs
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            state: present
            api_version: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            name: cert-manager-controller-clusterissuers-ejbca
            definition:
              rules:
                - verbs:
                    - update
                    - patch
                  apiGroups:
                    - ejbca-issuer.keyfactor.com
                    - cert-manager.io
                  resources:
                    - clusterissuers
                    - clusterissuers/status
                - verbs:
                    - get
                    - list
                    - watch
                  apiGroups:
                    - cert-manager.io
                    - ejbca-issuer.keyfactor.com
                  resources:
                    - clusterissuers
 
        - name: Added the ClusterRole to allow for cert-manager to approve certs for the EJBCA ClusterIssuer certs
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            state: present
            api_version: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            name: cert-manager-controller-approve-ejbca:cert-manager-io
            definition:
              rules:
                - verbs:
                    - approve
                  apiGroups:
                    - ejbca-issuer.keyfactor.com
                    - cert-manager.io
                  resources:
                    - signers
                  resourceNames:
                    - clusterissuers.ejbca-issuer.keyfactor.com/*
                    - issuers.ejbca-issuer.keyfactor.com/*
                    - issuers.cert-manager.io/*
                    - clusterissuers.cert-manager.io/*

        - name: Add the RoleBinding to the cert-manager service account
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            state: present
            api_version: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            name: ejbca-cert-manager-controller-clusterissuers
            definition:
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cert-manager-controller-clusterissuers-ejbca
              subjects:
                - kind: ServiceAccount
                  name: cert-manager
                  namespace: cert-manager

        - name: Add the RoleBinding to the cert-manager service account for approvel
          kubernetes.core.k8s:
            kubeconfig: "{{ kubeconfig }}"
            state: present
            api_version: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            name: ejbca-cert-manager-controller-approve:cert-manager-io
            definition:
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cert-manager-controller-approve-ejbca:cert-manager-io
              subjects:
                - kind: ServiceAccount
                  name: cert-manager
                  namespace: cert-manager
```

**Comment by 13567436138** [comment]
I face the same issuer,after add the permissions:
```
2025-12-19T06:49:58Z    ERROR   Reconciler error        {"controller": "certificaterequest", "controllerGroup": "cert-manager.io", "controllerKind": "CertificateRequest", "CertificateRequest": {"name":"test-1","namespace":"ejbca-cert-manager"}, "namespace": "ejbca-cert-manager", "name": "test-1", "reconcileID": "24d89b30-2607-4cb6-a5af-5f83ea73560a", "error": "failed to sign: failed to enroll CSR - 403 Forbidden - EJBCA API returned error {\"error_code\":403,\"error_message\":\"Error no client certificate or OAuth token received for authentication.\"}"}
```

```
kubectl -n ejbca-cert-manager create secret tls ejbca-secret --cert=cert-manager-ra-01.crt --key=cert-manager-ra-01-key.pem

#kubectl -n ejbca-cert-manager create secret generic ejbca-ca-secret --from-file=ca.crt=ManagementCA.crt

kubectl -n ejbca-cert-manager create secret generic ejbca-ca-secret --from-file=ca.crt=ejbca-ingress-ca.crt 


cat <<EOF|kubectl apply -n ejbca-cert-manager -f -
apiVersion: ejbca-issuer.keyfactor.com/v1alpha1
kind: Issuer
metadata:
  name: test
spec:
  hostname: "ejbca.mark.demo"
  ejbcaSecretName: "ejbca-secret"
  certificateAuthorityName: "fulcio-ca"
  certificateProfileName: "fulcio-enduser"
  endEntityProfileName: "cosign Server Profile"
  caBundleSecretName: ejbca-ca-secret
EOF


cat <<EOF|kubectl apply -n ejbca-cert-manager -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
spec:
  subject:
    countries:
      - SE
    organizations:
      - Keyfactor Community
  commonName: fulcio.mark.demo
  dnsNames:
   - fulcio.mark.demo
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: test
  issuerRef:
    name: test
    group: ejbca-issuer.keyfactor.com
    kind: Issuer
EOF
```
